In [1]:
!pip install yfinance pandas matplotlib seaborn

Requirement already satisfied: yfinance in c:\users\anburaj\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: pandas in c:\users\anburaj\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in c:\users\anburaj\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\anburaj\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (4.0.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\anburaj\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anburaj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anburaj\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\anburaj\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\anburaj\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anburaj\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\anburaj\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\anburaj\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\anburaj\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\anburaj\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\anburaj\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\anburaj\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\anburaj\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\anburaj\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.1.4)
Requirement already satisfied: rich in c:\users\anburaj\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in c:\users\anburaj\anaconda3\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in c:\users\anburaj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anburaj\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anburaj\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anburaj\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\anburaj\anaconda3\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\anburaj\anaconda3\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\anburaj\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

In [2]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [5]:
brent = yf.download(
    "BZ=F",
     start = "2020-01-01",
     end = "2026-04-30"
)

[*********************100%***********************]  1 of 1 completed

In [6]:
brent.head()

Price           Close       High        Low       Open Volume
Ticker           BZ=F       BZ=F       BZ=F       BZ=F   BZ=F
Date
2020-01-02  66.250000  66.570000  65.730003  66.470001  25810
2020-01-03  68.599998  69.480003  66.220001  66.290001  78848
2020-01-06  68.910004  70.720001  68.190002  69.070000  51933
2020-01-07  68.269997  68.739998  67.650002  68.580002  41178
2020-01-08  65.440002  71.989998  64.940002  68.470001  85232

In [7]:
brent.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1592 entries, 2020-01-02 to 2026-04-29
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, BZ=F)   1592 non-null   float64
 1   (High, BZ=F)    1592 non-null   float64
 2   (Low, BZ=F)     1592 non-null   float64
 3   (Open, BZ=F)    1592 non-null   float64
 4   (Volume, BZ=F)  1592 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 74.6 KB

In [8]:
brent.describe()

Price         Close         High          Low         Open         Volume
Ticker         BZ=F         BZ=F         BZ=F         BZ=F           BZ=F
count   1592.000000  1592.000000  1592.000000  1592.000000    1592.000000
mean      74.353763    75.597425    73.030044    74.317682   33598.273241
std       18.902730    19.294111    18.450726    18.842415   18886.934042
min       19.330000    21.270000    16.000000    19.559999       0.000000
25%       65.239998    66.017498    64.225002    65.207499   23562.750000
50%       75.165001    76.299999    74.174999    75.209999   30749.000000
75%       84.892500    85.827499    83.752501    84.892500   39570.750000
max      127.980003   137.000000   122.500000   129.570007  235965.000000

In [9]:
brent.columns = ['Close', 'High', 'Low', 'Open', 'Volume']

brent.reset_index(inplace=True)

brent.head()

        Date      Close       High        Low       Open  Volume
0 2020-01-02  66.250000  66.570000  65.730003  66.470001   25810
1 2020-01-03  68.599998  69.480003  66.220001  66.290001   78848
2 2020-01-06  68.910004  70.720001  68.190002  69.070000   51933
3 2020-01-07  68.269997  68.739998  67.650002  68.580002   41178
4 2020-01-08  65.440002  71.989998  64.940002  68.470001   85232

In [10]:
brent.to_csv("brent_oil_clean.csv", index=False)

In [11]:
assets = {
    "Brent": "BZ=F",
    "WTI": "CL=F",
    "Gold": "GC=F",
    "SP500": "^GSPC",
    "NASDAQ": "^IXIC",
    "VIX": "^VIX",
    "USD_Index": "DX-Y.NYB",
    "INR_USD": "INR=X",
    
    "Lockheed": "LMT",
    "Raytheon": "RTX",
    "Delta": "DAL",
    "American_Airlines": "AAL"
}

In [13]:
market_data = {}

In [14]:
for name, ticker in assets.items():
    
    data = yf.download(
        ticker,
        start="2020-01-01",
        end="2026-04-30"
    )
    
    data.columns = ['Close', 'High', 'Low', 'Open', 'Volume']
    
    data.reset_index(inplace=True)
    
    market_data[name] = data
    
    print(f"{name} data downloaded")

[*********************100%***********************]  1 of 1 completed

Brent data downloaded

[*********************100%***********************]  1 of 1 completed

WTI data downloaded

[*********************100%***********************]  1 of 1 completed

Gold data downloaded

[*********************100%***********************]  1 of 1 completed

SP500 data downloaded

[*********************100%***********************]  1 of 1 completed

NASDAQ data downloaded

[*********************100%***********************]  1 of 1 completed

VIX data downloaded

[*********************100%***********************]  1 of 1 completed

USD_Index data downloaded

[*********************100%***********************]  1 of 1 completed

INR_USD data downloaded

[*********************100%***********************]  1 of 1 completed

Lockheed data downloaded

[*********************100%***********************]  1 of 1 completed

Raytheon data downloaded

[*********************100%***********************]  1 of 1 completed

Delta data downloaded

[*********************100%***********************]  1 of 1 completed

American_Airlines data downloaded

In [16]:
market_data['Gold'].head()

        Date        Close         High          Low         Open  Volume
0 2020-01-02  1524.500000  1528.699951  1518.000000  1518.099976     214
1 2020-01-03  1549.199951  1552.699951  1530.099976  1530.099976     107
2 2020-01-06  1566.199951  1580.000000  1560.400024  1580.000000     416
3 2020-01-07  1571.800049  1576.300049  1558.300049  1558.300049      47
4 2020-01-08  1557.400024  1604.199951  1552.300049  1579.699951     236

In [17]:
market_data["SP500"][["Date", "Close"]].head()

        Date        Close
0 2020-01-02  3257.850098
1 2020-01-03  3234.850098
2 2020-01-06  3246.280029
3 2020-01-07  3237.179932
4 2020-01-08  3253.050049

In [20]:
brent_df = market_data["Brent"][["Date", "Close"]].copy()

gold_df = market_data["Gold"][["Date", "Close"]].copy()

In [21]:
brent_df.rename(columns={"Close": "Brent"}, inplace=True)

gold_df.rename(columns={"Close": "Gold"}, inplace=True)

In [22]:
merged_df = pd.merge(
    brent_df,
    gold_df,
    on="Date"
)

merged_df.head()

        Date      Brent         Gold
0 2020-01-02  66.250000  1524.500000
1 2020-01-03  68.599998  1549.199951
2 2020-01-06  68.910004  1566.199951
3 2020-01-07  68.269997  1571.800049
4 2020-01-08  65.440002  1557.400024

In [23]:
master_df = None

for name, data in market_data.items():
    
    temp_df = data[["Date", "Close"]].copy()
    
    temp_df.rename(columns={"Close": name}, inplace=True)
    
    if master_df is None:
        master_df = temp_df
    else:
        master_df = pd.merge(
            master_df,
            temp_df,
            on="Date"
        )

master_df.head()

,Date,Brent,WTI,Gold,SP500,NASDAQ,VIX,USD_Index,INR_USD,Lockheed,Raytheon,Delta,American_Airlines
0,2020-01-02,66.250000,61.180000,1524.500000,3257.850098,9092.190430,12.47,96.849998,71.025002,337.609253,83.261871,56.887684,28.982893
1,2020-01-03,68.599998,63.049999,1549.199951,3234.850098,9020.769531,14.02,96.839996,71.415001,349.756989,83.376045,55.943413,27.548195
2,2020-01-06,68.910004,63.270000,1566.199951,3246.280029,9071.469727,13.85,96.669998,71.731003,349.224335,83.555428,55.557991,27.219410
3,2020-01-07,68.269997,62.700001,1571.800049,3237.179932,9068.580078,13.79,96.980003,71.787003,350.399445,83.289062,55.509819,27.119778
4,2020-01-08,65.440002,59.610001,1557.400024,3253.050049,9129.240234,13.45,97.300003,72.160004,347.466064,83.414108,56.704605,27.737495

In [24]:
master_df.isnull().sum()

Date                 0
Brent                0
WTI                  0
Gold                 0
SP500                0
NASDAQ               0
VIX                  0
USD_Index            0
INR_USD              0
Lockheed             0
Raytheon             0
Delta                0
American_Airlines    0
dtype: int64

In [25]:
master_df.to_csv("master_market_data.csv", index=False)

In [26]:
master_df["Brent_Return"] = master_df["Brent"].pct_change() * 100

master_df[["Date", "Brent", "Brent_Return"]].head()

        Date      Brent  Brent_Return
0 2020-01-02  66.250000           NaN
1 2020-01-03  68.599998      3.547168
2 2020-01-06  68.910004      0.451903
3 2020-01-07  68.269997     -0.928758
4 2020-01-08  65.440002     -4.145297

In [27]:
return_columns = [
    "Brent",
    "WTI",
    "Gold",
    "SP500",
    "NASDAQ",
    "VIX",
    "USD_Index",
    "INR_USD",
    "Lockheed",
    "Raytheon",
    "Delta",
    "American_Airlines"
]

for col in return_columns:
    
    master_df[f"{col}_Return"] = master_df[col].pct_change() * 100

In [28]:
master_df.head()

,Date,Brent,WTI,Gold,SP500,NASDAQ,VIX,USD_Index,INR_USD,Lockheed,...,Gold_Return,SP500_Return,NASDAQ_Return,VIX_Return,USD_Index_Return,INR_USD_Return,Lockheed_Return,Raytheon_Return,Delta_Return,American_Airlines_Return
0,2020-01-02,66.250000,61.180000,1524.500000,3257.850098,9092.190430,12.47,96.849998,71.025002,337.609253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-03,68.599998,63.049999,1549.199951,3234.850098,9020.769531,14.02,96.839996,71.415001,349.756989,...,1.620200,-0.705987,-0.785519,12.429833,-0.010327,0.549102,3.598164,0.137126,-1.659887,-4.950155
2,2020-01-06,68.910004,63.270000,1566.199951,3246.280029,9071.469727,13.85,96.669998,71.731003,349.224335,...,1.097341,0.353337,0.562038,-1.212554,-0.175545,0.442487,-0.152293,0.215149,-0.688949,-1.193490
3,2020-01-07,68.269997,62.700001,1571.800049,3237.179932,9068.580078,13.79,96.980003,71.787003,350.399445,...,0.357560,-0.280324,-0.031854,-0.433216,0.320684,0.078069,0.336491,-0.318788,-0.086706,-0.366034
4,2020-01-08,65.440002,59.610001,1557.400024,3253.050049,9129.240234,13.45,97.300003,72.160004,347.466064,...,-0.916149,0.490245,0.668905,-2.465556,0.329965,0.519594,-0.837153,0.150135,2.152387,2.277739

In [29]:
master_df["Brent_MA7"] = (
    master_df["Brent"]
    .rolling(window=7)
    .mean()
)

master_df[["Date", "Brent", "Brent_MA7"]].head(10)

        Date      Brent  Brent_MA7
0 2020-01-02  66.250000        NaN
1 2020-01-03  68.599998        NaN
2 2020-01-06  68.910004        NaN
3 2020-01-07  68.269997        NaN
4 2020-01-08  65.440002        NaN
5 2020-01-09  65.370003        NaN
6 2020-01-10  64.980003  66.831430
7 2020-01-13  64.199997  66.538572
8 2020-01-14  64.489998  65.951429
9 2020-01-15  64.000000  65.250000

In [30]:
master_df["Brent_Volatility"] = (
    master_df["Brent_Return"]
    .rolling(window=7)
    .std()
)

master_df[
    ["Date", "Brent_Return", "Brent_Volatility"]
].head(15)

         Date  Brent_Return  Brent_Volatility
0  2020-01-02           NaN               NaN
1  2020-01-03      3.547168               NaN
2  2020-01-06      0.451903               NaN
3  2020-01-07     -0.928758               NaN
4  2020-01-08     -4.145297               NaN
5  2020-01-09     -0.106968               NaN
6  2020-01-10     -0.596603               NaN
7  2020-01-13     -1.200379          2.286674
8  2020-01-14      0.451715          1.580689
9  2020-01-15     -0.759804          1.474892
10 2020-01-16      0.968754          1.661500
11 2020-01-17      0.355920          0.768365
12 2020-01-21     -0.400929          0.775107
13 2020-01-22     -2.136550          1.076654
14 2020-01-23     -1.850970          1.181382

In [33]:
master_df["Market_Regime"] = "Recovery"

master_df.loc[
    (master_df["Date"] >= "2020-01-01") &
    (master_df["Date"] <= "2021-12-31"),
    "Market_Regime"
] = "COVID Era"

master_df.loc[
    (master_df["Date"] >= "2026-02-28"),
    "Market_Regime"
] = "Iran Escalation"

In [34]:
master_df[["Date", "Market_Regime"]].sample(10)

           Date Market_Regime
413  2021-08-23     COVID Era
800  2023-03-08      Recovery
948  2023-10-09      Recovery
424  2021-09-08     COVID Era
799  2023-03-07      Recovery
936  2023-09-21      Recovery
696  2022-10-06      Recovery
951  2023-10-12      Recovery
1129 2024-06-28      Recovery
1362 2025-06-05      Recovery

In [35]:
events = pd.DataFrame({
    "Date": [
        "2020-03-11",
        "2020-04-20",
        "2022-02-24",
        "2026-03-02"
    ],
    
    "Event": [
        "COVID Pandemic Declared",
        "WTI Oil Crash",
        "Russia-Ukraine War",
        "Iran Escalation"
    ]
})

events

         Date                    Event
0  2020-03-11  COVID Pandemic Declared
1  2020-04-20            WTI Oil Crash
2  2022-02-24       Russia-Ukraine War
3  2026-03-02          Iran Escalation

In [2]:
max_brent_spike = master_df["Brent_Return"].max()

max_brent_spike

NameError: name 'master_df' is not defined

In [37]:
max_brent_drop = master_df["Brent_Return"].min()

max_brent_drop

-24.40359736250306

In [38]:
avg_brent_volatility = master_df["Brent_Volatility"].mean()

avg_brent_volatility

np.float64(2.246324526473626)

In [39]:
max_vix_spike = master_df["VIX_Return"].max()

max_vix_spike

74.03907396600702

In [40]:
worst_airline_drop = master_df[
    ["Delta_Return", "American_Airlines_Return"]
].min().min()

worst_airline_drop

-25.992449206438284

In [6]:
master_df.columns

Index(['Date', 'Brent', 'WTI', 'Gold', 'SP500', 'NASDAQ', 'VIX', 'USD_Index',
       'INR_USD', 'Lockheed', 'Raytheon', 'Delta', 'American_Airlines'],
      dtype='object')

In [7]:
return_columns = [
    "Brent",
    "WTI",
    "Gold",
    "SP500",
    "NASDAQ",
    "VIX",
    "USD_Index",
    "INR_USD",
    "Lockheed",
    "Raytheon",
    "Delta",
    "American_Airlines"
]

for col in return_columns:
    
    master_df[f"{col}_Return"] = (
        master_df[col].pct_change() * 100
    )

In [8]:
master_df["Brent_MA7"] = (
    master_df["Brent"]
    .rolling(window=7)
    .mean()
)

In [9]:
master_df["Brent_Volatility"] = (
    master_df["Brent_Return"]
    .rolling(window=7)
    .std()
)

In [10]:
master_df["Market_Regime"] = "Recovery"

master_df.loc[
    (master_df["Date"] >= "2020-01-01") &
    (master_df["Date"] <= "2021-12-31"),
    "Market_Regime"
] = "COVID Era"

master_df.loc[
    (master_df["Date"] >= "2026-03-02"),
    "Market_Regime"
] = "Iran Escalation"

In [12]:
master_df.columns

Index(['Date', 'Brent', 'WTI', 'Gold', 'SP500', 'NASDAQ', 'VIX', 'USD_Index',
       'INR_USD', 'Lockheed', 'Raytheon', 'Delta', 'American_Airlines',
       'Brent_Return', 'WTI_Return', 'Gold_Return', 'SP500_Return',
       'NASDAQ_Return', 'VIX_Return', 'USD_Index_Return', 'INR_USD_Return',
       'Lockheed_Return', 'Raytheon_Return', 'Delta_Return',
       'American_Airlines_Return', 'Brent_MA7', 'Brent_Volatility',
       'Market_Regime'],
      dtype='object')

In [13]:
max_brent_spike = round(
    master_df["Brent_Return"].max(), 2
)

max_brent_drop = round(
    master_df["Brent_Return"].min(), 2
)

avg_brent_volatility = round(
    master_df["Brent_Volatility"].mean(), 2
)

max_vix_spike = round(
    master_df["VIX_Return"].max(), 2
)

worst_airline_drop = round(
    master_df[
        ["Delta_Return", "American_Airlines_Return"]
    ].min().min(), 2
)

In [14]:
kpi_df = pd.DataFrame({
    "KPI": [
        "Max Brent Spike %",
        "Max Brent Drop %",
        "Average Brent Volatility",
        "Max VIX Spike %",
        "Worst Airline Drop %"
    ],
    
    "Value": [
        max_brent_spike,
        max_brent_drop,
        avg_brent_volatility,
        max_vix_spike,
        worst_airline_drop
    ]
})

kpi_df

                        KPI  Value
0         Max Brent Spike %  21.02
1          Max Brent Drop % -24.40
2  Average Brent Volatility   2.25
3           Max VIX Spike %  74.04
4      Worst Airline Drop % -25.99

In [15]:
best_defense_gain = round(
    master_df[
        ["Lockheed_Return", "Raytheon_Return"]
    ].max().max(), 2
)

worst_sp500_drop = round(
    master_df["SP500_Return"].min(), 2
)

max_gold_spike = round(
    master_df["Gold_Return"].max(), 2
)

In [16]:
kpi_df = pd.DataFrame({
    "KPI": [
        "Max Brent Spike %",
        "Max Brent Drop %",
        "Average Brent Volatility",
        "Max VIX Spike %",
        "Worst Airline Drop %",
        "Best Defense Stock Gain %",
        "Worst SP500 Drop %",
        "Max Gold Spike %"
    ],
    
    "Value": [
        max_brent_spike,
        max_brent_drop,
        avg_brent_volatility,
        max_vix_spike,
        worst_airline_drop,
        best_defense_gain,
        worst_sp500_drop,
        max_gold_spike
    ]
})

kpi_df

                         KPI  Value
0          Max Brent Spike %  21.02
1           Max Brent Drop % -24.40
2   Average Brent Volatility   2.25
3            Max VIX Spike %  74.04
4       Worst Airline Drop % -25.99
5  Best Defense Stock Gain %  15.76
6         Worst SP500 Drop % -11.98
7           Max Gold Spike %   6.08

In [17]:
master_df["Oil_Shock"] = (
    abs(master_df["Brent_Return"]) > 5
)

In [18]:
master_df[
    master_df["Oil_Shock"] == True
][
    ["Date", "Brent_Return", "Market_Regime"]
].head(20)

          Date  Brent_Return Market_Regime
21  2020-02-03     -6.378953     COVID Era
44  2020-03-06     -9.441891     COVID Era
45  2020-03-09    -24.099845     COVID Era
46  2020-03-10      8.323634     COVID Era
48  2020-03-12     -7.180776     COVID Era
50  2020-03-16    -11.225995     COVID Era
52  2020-03-18    -13.400628     COVID Era
53  2020-03-19     14.429262     COVID Era
54  2020-03-20     -5.233579     COVID Era
59  2020-03-27     -5.353075     COVID Era
60  2020-03-30     -8.704372     COVID Era
62  2020-04-01      8.795075     COVID Era
63  2020-04-02     21.018597     COVID Era
64  2020-04-03     13.927856     COVID Era
70  2020-04-14     -6.742279     COVID Era
71  2020-04-15     -6.452702     COVID Era
74  2020-04-20     -8.938747     COVID Era
75  2020-04-21    -24.403597     COVID Era
76  2020-04-22      5.380243     COVID Era
79  2020-04-27     -6.763063     COVID Era

In [19]:
shock_summary = (
    master_df[master_df["Oil_Shock"] == True]
    .groupby("Market_Regime")
    .size()
    .reset_index(name="Shock_Days")
)

shock_summary

     Market_Regime  Shock_Days
0        COVID Era          40
1  Iran Escalation          13
2         Recovery          37

In [20]:
master_df.to_csv(
    "master_market_features.csv",
    index=False
)

In [21]:
kpi_df.to_csv(
    "kpi_summary.csv",
    index=False
)

In [23]:
shock_summary.to_csv(
    "shock_summary.csv",
    index=False
)

In [24]:
events = pd.DataFrame({
    "Date": [
        "2020-03-11",
        "2020-04-20",
        "2022-02-24",
        "2026-03-02"
    ],
    
    "Event": [
        "COVID Pandemic Declared",
        "WTI Oil Crash",
        "Russia-Ukraine War",
        "Iran Escalation"
    ]
})

events

         Date                    Event
0  2020-03-11  COVID Pandemic Declared
1  2020-04-20            WTI Oil Crash
2  2022-02-24       Russia-Ukraine War
3  2026-03-02          Iran Escalation

In [25]:
events.to_csv(
    "events.csv",
    index=False
)

In [26]:
correlation_columns = [
    "Brent_Return",
    "Gold_Return",
    "SP500_Return",
    "NASDAQ_Return",
    "VIX_Return",
    "USD_Index_Return",
    "Delta_Return",
    "Lockheed_Return"
]

correlation_df = master_df[
    correlation_columns
]

correlation_df.head()

,Brent_Return,Gold_Return,SP500_Return,NASDAQ_Return,VIX_Return,USD_Index_Return,Delta_Return,Lockheed_Return
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.547168,1.620200,-0.705987,-0.785519,12.429833,-0.010327,-1.659887,3.598164
2,0.451903,1.097341,0.353337,0.562038,-1.212554,-0.175545,-0.688949,-0.152293
3,-0.928758,0.357560,-0.280324,-0.031854,-0.433216,0.320684,-0.086706,0.336491
4,-4.145297,-0.916149,0.490245,0.668905,-2.465556,0.329965,2.152387,-0.837153

In [27]:
correlation_matrix = correlation_df.corr()

correlation_matrix

,Brent_Return,Gold_Return,SP500_Return,NASDAQ_Return,VIX_Return,USD_Index_Return,Delta_Return,Lockheed_Return
Brent_Return,1.000000,0.086653,0.206653,0.156196,-0.161223,-0.004737,0.090635,0.181247
Gold_Return,0.086653,1.000000,0.112005,0.112119,-0.039478,-0.367438,0.010304,0.089914
SP500_Return,0.206653,0.112005,1.000000,0.949507,-0.717564,-0.174561,0.578361,0.407297
NASDAQ_Return,0.156196,0.112119,0.949507,1.000000,-0.707274,-0.168206,0.500716,0.265643
VIX_Return,-0.161223,-0.039478,-0.717564,-0.707274,1.000000,0.105411,-0.441302,-0.212150
USD_Index_Return,-0.004737,-0.367438,-0.174561,-0.168206,0.105411,1.000000,-0.171310,-0.019781
Delta_Return,0.090635,0.010304,0.578361,0.500716,-0.441302,-0.171310,1.000000,0.203306
Lockheed_Return,0.181247,0.089914,0.407297,0.265643,-0.212150,-0.019781,0.203306,1.000000

In [28]:
correlation_matrix.to_csv(
    "correlation_matrix.csv"
)

In [29]:
headlines = pd.DataFrame({

    "Date": [
        "2020-03-11",
        "2020-04-20",
        "2020-11-09",
        "2022-02-24",
        "2022-03-08",
        "2023-10-07",

        "2026-03-02",
        "2026-03-18",
        "2026-04-13",
        "2026-04-27",
        "2026-05-07",
        "2026-05-10"
    ],

    "Headline": [
        "WHO declares COVID-19 a global pandemic",
        "WTI crude oil futures collapse below zero",
        "Pfizer announces successful vaccine results",
        "Russia launches military operation in Ukraine",
        "Oil prices surge amid global supply fears",
        "Middle East tensions trigger market uncertainty",

        "Iran escalation raises fears of regional conflict",
        "South Pars energy facility attack disrupts gas supply",
        "US naval blockade intensifies Strait of Hormuz crisis",
        "Oil prices rise as US-Iran peace talks stall",
        "US launches strikes amid renewed Iran tensions",
        "Markets remain volatile amid ongoing oil supply fears"
    ],

    "Sentiment": [
        "Negative",
        "Negative",
        "Positive",
        "Negative",
        "Negative",
        "Negative",

        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Neutral"
    ],

    "Category": [
        "Health Crisis",
        "Oil Market",
        "Recovery",
        "War",
        "Oil Market",
        "Geopolitics",

        "War",
        "Energy Infrastructure",
        "Geopolitics",
        "Oil Market",
        "War",
        "Markets"
    ]

})

headlines

,Date,Headline,Sentiment,Category
0,2020-03-11,WHO declares COVID-19 a global pandemic,Negative,Health Crisis
1,2020-04-20,WTI crude oil futures collapse below zero,Negative,Oil Market
2,2020-11-09,Pfizer announces successful vaccine results,Positive,Recovery
3,2022-02-24,Russia launches military operation in Ukraine,Negative,War
4,2022-03-08,Oil prices surge amid global supply fears,Negative,Oil Market
5,2023-10-07,Middle East tensions trigger market uncertainty,Negative,Geopolitics
6,2026-03-02,Iran escalation raises fears of regional conflict,Negative,War
7,2026-03-18,South Pars energy facility attack disrupts gas...,Negative,Energy Infrastructure
8,2026-04-13,US naval blockade intensifies Strait of Hormuz...,Negative,Geopolitics
9,2026-04-27,Oil prices rise as US-Iran peace talks stall,Negative,Oil Market
10,2026-05-07,US launches strikes amid renewed Iran tensions,Negative,War
11,2026-05-10,Markets remain volatile amid ongoing oil suppl...,Neutral,Markets

In [30]:
headlines.to_csv(
    "headline_sentiment.csv",
    index=False
)

In [2]:
import yfinance as yf
import pandas as pd

In [3]:
natural_gas = yf.download(
    "NG=F",
    start="2020-01-02",
    end="2026-05-11"
)

wheat = yf.download(
    "ZW=F",
    start="2020-01-02",
    end="2026-05-11"
)

copper = yf.download(
    "HG=F",
    start="2020-01-02",
    end="2026-05-11"
)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [4]:
natural_gas = natural_gas[["Close"]]
natural_gas.columns = ["NaturalGas"]

wheat = wheat[["Close"]]
wheat.columns = ["Wheat"]

copper = copper[["Close"]]
copper.columns = ["Copper"]

In [6]:
natural_gas = natural_gas.reset_index()
wheat = wheat.reset_index()
copper = copper.reset_index()

In [8]:
master_df["Date"] = pd.to_datetime(master_df["Date"])

natural_gas["Date"] = pd.to_datetime(natural_gas["Date"])
wheat["Date"] = pd.to_datetime(wheat["Date"])
copper["Date"] = pd.to_datetime(copper["Date"])

In [9]:
master_df = master_df.merge(
    natural_gas,
    on="Date",
    how="left"
)

master_df = master_df.merge(
    wheat,
    on="Date",
    how="left"
)

master_df = master_df.merge(
    copper,
    on="Date",
    how="left"
)

In [10]:
master_df[
[
"Date",
"NaturalGas",
"Wheat",
"Copper"
]
].head()

        Date  NaturalGas   Wheat  Copper
0 2020-01-02       2.122  560.25  2.8330
1 2020-01-03       2.130  554.50  2.7985
2 2020-01-06       2.135  550.00  2.8005
3 2020-01-07       2.162  550.25  2.8040
4 2020-01-08       2.141  552.75  2.8190

In [11]:
master_df["NaturalGas_Return"] = (
    master_df["NaturalGas"].pct_change() * 100
)

master_df["Wheat_Return"] = (
    master_df["Wheat"].pct_change() * 100
)

master_df["Copper_Return"] = (
    master_df["Copper"].pct_change() * 100
)

In [12]:
master_df[
[
"Date",
"NaturalGas_Return",
"Wheat_Return",
"Copper_Return"
]
].head()

        Date  NaturalGas_Return  Wheat_Return  Copper_Return
0 2020-01-02                NaN           NaN            NaN
1 2020-01-03           0.377009     -1.026328      -1.217786
2 2020-01-06           0.234736     -0.811542       0.071462
3 2020-01-07           1.264635      0.045455       0.124977
4 2020-01-08          -0.971319      0.454339       0.534954

In [13]:
master_df.to_csv(
    "master_market_features.csv",
    index=False
)

In [15]:
master_df.to_csv(
r"C:\Users\anburaj\Desktop\job\pro 3\impact\master_market_features.csv",
index=False
)

In [16]:
master_df.to_csv(
"C:/Users/anburaj/Desktop/job/pro 3/impact/master_market_features.csv",
index=False
)